<link rel="stylesheet" href="../css/style_3.css">
<style>
    /*!
Chosen, a Select Box Enhancer for jQuery and Prototype
by Patrick Filler for Harvest, http://getharvest.com

Version 1.1.0
Full source at https://github.com/harvesthq/chosen
Copyright (c) 2011 Harvest http://getharvest.com

MIT License, https://github.com/harvesthq/chosen/blob/master/LICENSE.md
This file is generated by `grunt build`, do not edit it by hand.
*/

    /* @group Base */
    .chosen-container {
        position: relative;
        display: inline-block;
        vertical-align: middle;
        font-size: 13px;
        zoom: 1;
        *display: inline;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
        width: 100% !important;
    }
    .chosen-container .chosen-drop {
        position: absolute;
        top: 100%;
        left: -9999px;
        z-index: 1010;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        width: 100%;
        border: 1px solid #aaa;
        border-top: 0;
        background: #fff;
        box-shadow: 0 4px 5px rgba(0, 0, 0, 0.15);
    }
    .chosen-container.chosen-with-drop .chosen-drop {
        left: 0;
    }
    .chosen-container a {
        cursor: pointer;
    }

    /* @end */
    /* @group Single Chosen */
    .chosen-container-single .chosen-single {
        position: relative;
        display: block;
        overflow: hidden;
        padding: 0 0 0 8px;
        height: 23px;
        border: 1px solid #aaa;
        border-radius: 5px;
        background-color: #fff;
        background: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(20%, #ffffff), color-stop(50%, #f6f6f6), color-stop(52%, #eeeeee), color-stop(100%, #f4f4f4));
        background: -webkit-linear-gradient(top, #ffffff 20%, #f6f6f6 50%, #eeeeee 52%, #f4f4f4 100%);
        background: -moz-linear-gradient(top, #ffffff 20%, #f6f6f6 50%, #eeeeee 52%, #f4f4f4 100%);
        background: -o-linear-gradient(top, #ffffff 20%, #f6f6f6 50%, #eeeeee 52%, #f4f4f4 100%);
        background: linear-gradient(top, #ffffff 20%, #f6f6f6 50%, #eeeeee 52%, #f4f4f4 100%);
        background-clip: padding-box;
        box-shadow: 0 0 3px white inset, 0 1px 1px rgba(0, 0, 0, 0.1);
        color: #444;
        text-decoration: none;
        white-space: nowrap;
        line-height: 24px;
    }
    .chosen-container-single .chosen-default {
        color: #999;
    }
    .chosen-container-single .chosen-single span {
        display: block;
        overflow: hidden;
        margin-right: 26px;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
    .chosen-container-single .chosen-single-with-deselect span {
        margin-right: 38px;
    }
    .chosen-container-single .chosen-single abbr {
        position: absolute;
        top: 6px;
        right: 26px;
        display: block;
        width: 12px;
        height: 12px;
        background: url('chosen-sprite.png') -42px 1px no-repeat;
        font-size: 1px;
    }
    .chosen-container-single .chosen-single abbr:hover {
        background-position: -42px -10px;
    }
    .chosen-container-single.chosen-disabled .chosen-single abbr:hover {
        background-position: -42px -10px;
    }
    .chosen-container-single .chosen-single div {
        position: absolute;
        top: 0;
        right: 0;
        display: block;
        width: 18px;
        height: 100%;
    }
    .chosen-container-single .chosen-single div b {
        display: block;
        width: 100%;
        height: 100%;
        background: url('chosen-sprite.png') no-repeat 0px 7px;
    }
    .chosen-container-single .chosen-search {
        position: relative;
        z-index: 1010;
        margin: 0;
        padding: 3px 4px;
        white-space: nowrap;
    }
    .chosen-container-single .chosen-search input[type="text"] {
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        margin: 1px 0;
        padding: 4px 20px 4px 5px;
        width: 100%;
        height: auto;
        outline: 0;
        border: 1px solid #aaa;
        background: white url('chosen-sprite.png') no-repeat 100% -20px;
        background: url('chosen-sprite.png') no-repeat 100% -20px;
        font-size: 1em;
        font-family: sans-serif;
        line-height: normal;
        border-radius: 0;
    }
    .chosen-container-single .chosen-drop {
        margin-top: -1px;
        border-radius: 0 0 4px 4px;
        background-clip: padding-box;
    }
    .chosen-container-single.chosen-container-single-nosearch .chosen-search {
        position: absolute;
        left: -9999px;
    }

    /* @end */
    /* @group Results */
    .chosen-container .chosen-results {
        position: relative;
        overflow-x: hidden;
        overflow-y: auto;
        margin: 0 4px 4px 0;
        padding: 0 0 0 4px;
        max-height: 240px;
        -webkit-overflow-scrolling: touch;
    }
    .chosen-container .chosen-results li {
        display: none;
        margin: 0;
        padding: 5px 6px;
        list-style: none;
        line-height: 15px;
        -webkit-touch-callout: none;
    }
    .chosen-container .chosen-results li.active-result {
        display: list-item;
        cursor: pointer;
    }
    .chosen-container .chosen-results li.disabled-result {
        display: list-item;
        color: #ccc;
        cursor: default;
    }
    .chosen-container .chosen-results li.highlighted {
        background-color: #3875d7;
        background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(20%, #3875d7), color-stop(90%, #2a62bc));
        background-image: -webkit-linear-gradient(#3875d7 20%, #2a62bc 90%);
        background-image: -moz-linear-gradient(#3875d7 20%, #2a62bc 90%);
        background-image: -o-linear-gradient(#3875d7 20%, #2a62bc 90%);
        background-image: linear-gradient(#3875d7 20%, #2a62bc 90%);
        color: #fff;
    }
    .chosen-container .chosen-results li.no-results {
        display: list-item;
        background: #f4f4f4;
    }
    .chosen-container .chosen-results li.group-result {
        display: list-item;
        font-weight: bold;
        cursor: default;
    }
    .chosen-container .chosen-results li.group-option {
        padding-left: 15px;
    }
    .chosen-container .chosen-results li em {
        font-style: normal;
        text-decoration: underline;
    }

    /* @end */
    /* @group Multi Chosen */
    .chosen-container-multi .chosen-choices {
        -moz-box-sizing: border-box;
        background-color: #FFFFFF;
        border: 1px solid #CCC;
        cursor: text;
        height: auto !important;
        margin: 0;
        min-height: 30px;
        overflow: hidden;
        padding: 2px;
        position: relative;
        width: 100%;
    }
    .chosen-container-multi .chosen-choices li {
        float: left;
        list-style: none;
    }
    .chosen-container-multi .chosen-choices li.search-field {
        margin: 0;
        padding: 0;
        white-space: nowrap;
    }
    .chosen-container-multi .chosen-choices li.search-field input[type="text"] {
        margin: 1px 0;
        padding: 5px;
        height: 25px;
        outline: 0;
        border: 0 !important;
        background: transparent !important;
        box-shadow: none;
        color: #666;
        font-size: 100%;
        font-family: sans-serif;
        line-height: normal;
        border-radius: 0;
    }
    .chosen-container-multi .chosen-choices li.search-field .default {
        color: #999;
    }
    .chosen-container-multi .chosen-choices li.search-choice {
        position: relative;
        margin: 3px 0 3px 5px;
        padding: 3px 20px 3px 5px;
        border: 1px solid #aaa;
        background-color: #e4e4e4;
        background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(20%, #f4f4f4), color-stop(50%, #f0f0f0), color-stop(52%, #e8e8e8), color-stop(100%, #eeeeee));
        background-image: -webkit-linear-gradient(#f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eeeeee 100%);
        background-image: -moz-linear-gradient(#f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eeeeee 100%);
        background-image: -o-linear-gradient(#f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eeeeee 100%);
        background-image: linear-gradient(#f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eeeeee 100%);
        background-clip: padding-box;
        box-shadow: 0 0 2px white inset, 0 1px 0 rgba(0, 0, 0, 0.05);
        color: #333;
        line-height: 13px;
        cursor: default;
    }
    .chosen-container-multi .chosen-choices li.search-choice .search-choice-close {
        position: absolute;
        top: 4px;
        right: 3px;
        display: block;
        width: 12px;
        height: 12px;
        background: url('chosen-sprite.png') -42px 1px no-repeat;
        font-size: 1px;
    }
    .chosen-container-multi .chosen-choices li.search-choice .search-choice-close:hover {
        background-position: -42px -10px;
    }
    .chosen-container-multi .chosen-choices li.search-choice-disabled {
        padding-right: 5px;
        border: 1px solid #ccc;
        background-color: #e4e4e4;
        background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(20%, #f4f4f4), color-stop(50%, #f0f0f0), color-stop(52%, #e8e8e8), color-stop(100%, #eeeeee));
        background-image: -webkit-linear-gradient(top, #f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eeeeee 100%);
        background-image: -moz-linear-gradient(top, #f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eeeeee 100%);
        background-image: -o-linear-gradient(top, #f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eeeeee 100%);
        background-image: linear-gradient(top, #f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eeeeee 100%);
        color: #666;
    }
    .chosen-container-multi .chosen-choices li.search-choice-focus {
        background: #d4d4d4;
    }
    .chosen-container-multi .chosen-choices li.search-choice-focus .search-choice-close {
        background-position: -42px -10px;
    }
    .chosen-container-multi .chosen-results {
        margin: 0;
        padding: 0;
    }
    .chosen-container-multi .chosen-drop .result-selected {
        display: list-item;
        color: #ccc;
        cursor: default;
    }

    /* @end */
    /* @group Active  */
    .chosen-container-active .chosen-single {
        border: 1px solid #5897fb;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
    }
    .chosen-container-active.chosen-with-drop .chosen-single {
        border: 1px solid #aaa;
        -moz-border-radius-bottomright: 0;
        border-bottom-right-radius: 0;
        -moz-border-radius-bottomleft: 0;
        border-bottom-left-radius: 0;
    }
    .chosen-container-active.chosen-with-drop .chosen-single div {
        border-left: none;
        background: transparent;
    }
    .chosen-container-active.chosen-with-drop .chosen-single div b {
        background-position: -18px 7px;
    }
    .chosen-container-active .chosen-choices {
        border: 1px solid #3bb4f2;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 5px rgba(59, 180, 242, 0.3);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 5px rgba(59, 180, 242, 0.3);
    }
    .chosen-container-active .chosen-choices li.search-field input[type="text"] {
        color: #111 !important;
    }

    /* @end */
    /* @group Disabled Support */
    .chosen-disabled {
        opacity: 0.5 !important;
        cursor: default;
    }
    .chosen-disabled .chosen-single {
        cursor: default;
    }
    .chosen-disabled .chosen-choices .search-choice .search-choice-close {
        cursor: default;
    }

    /* @end */
    /* @group Right to Left */
    .chosen-rtl {
        text-align: right;
    }
    .chosen-rtl .chosen-single {
        overflow: visible;
        padding: 0 8px 0 0;
    }
    .chosen-rtl .chosen-single span {
        margin-right: 0;
        margin-left: 26px;
        direction: rtl;
    }
    .chosen-rtl .chosen-single-with-deselect span {
        margin-left: 38px;
    }
    .chosen-rtl .chosen-single div {
        right: auto;
        left: 3px;
    }
    .chosen-rtl .chosen-single abbr {
        right: auto;
        left: 26px;
    }
    .chosen-rtl .chosen-choices li {
        float: right;
    }
    .chosen-rtl .chosen-choices li.search-field input[type="text"] {
        direction: rtl;
    }
    .chosen-rtl .chosen-choices li.search-choice {
        margin: 3px 5px 3px 0;
        padding: 3px 5px 3px 19px;
    }
    .chosen-rtl .chosen-choices li.search-choice .search-choice-close {
        right: auto;
        left: 4px;
    }
    .chosen-rtl.chosen-container-single-nosearch .chosen-search,
    .chosen-rtl .chosen-drop {
        left: 9999px;
    }
    .chosen-rtl.chosen-container-single .chosen-results {
        margin: 0 0 4px 4px;
        padding: 0 4px 0 0;
    }
    .chosen-rtl .chosen-results li.group-option {
        padding-right: 15px;
        padding-left: 0;
    }
    .chosen-rtl.chosen-container-active.chosen-with-drop .chosen-single div {
        border-right: none;
    }
    .chosen-rtl .chosen-search input[type="text"] {
        padding: 4px 5px 4px 20px;
        background: white url('chosen-sprite.png') no-repeat -30px -20px;
        background: url('chosen-sprite.png') no-repeat -30px -20px;
        direction: rtl;
    }
    .chosen-rtl.chosen-container-single .chosen-single div b {
        background-position: 6px 2px;
    }
    .chosen-rtl.chosen-container-single.chosen-with-drop .chosen-single div b {
        background-position: -12px 2px;
    }

    /* @end */
    /* @group Retina compatibility */
    @media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min-resolution: 144dpi) {
        .chosen-rtl .chosen-search input[type="text"],
        .chosen-container-single .chosen-single abbr,
        .chosen-container-single .chosen-single div b,
        .chosen-container-single .chosen-search input[type="text"],
        .chosen-container-multi .chosen-choices .search-choice .search-choice-close,
        .chosen-container .chosen-results-scroll-down span,
        .chosen-container .chosen-results-scroll-up span {
            background-image: url('chosen-sprite%402x.png') !important;
            background-size: 52px 37px !important;
            background-repeat: no-repeat !important;
        }
    }
    /* @end */

    body{
        color: black;
        overflow-y: scroll;
    }
    .mar-l-20 {
        margin-left: 80px;
    }

    .mar-r-20 {
        margin-right: 80px;
    }
    EGSYTZBP6Y
        /*slider样式*/
    .image-slider{
        width: 100%;
    }
    .image-slider-contents{
        width: 100%;
    }
    .image-slider-contents{
        overflow: visible;
    }
    .image-slider-forward,.image-slider-back{
        display: none !important;
    }
    .image-slider-contents .outer{
        width: 25%;
        margin: 0;
    }
    .cell{
        background-color: transparent;
        cursor: pointer;
    }

    .gr-nav{
        padding: 20px 0;
        text-align: center;
    }
    .gr-nav span{
        cursor: pointer;
        display: inline-block;
        color: #959595;
        line-height: 1;
        padding: 10px;
        border: 1px solid lightgray;
        margin: 0 5px;
        transition: 0.3s;
    }
    .span-active,.gr-nav span:hover{
        border:1px solid #00adee !important;
        background-color: #00adee;
        color: white !important;
    }
    .sanchu{
        display: inline-block;
        padding: 5px 8px;
        background-color: #d85030;
        color: white;
        cursor: pointer;
    }

    /*tab标签切换内容 css*/
    .tab-out{
        margin: 20px 0;
        border: 1px solid lightgray;
        padding: 20px;
    }
    .tab-out>div{
        display: none;
    }
    .am-radio-inline{
        padding-top: 0 !important;
    }
    [class*="am-u-"] + [class*="am-u-"]:last-child {
        float: left;
    }
    /*热卖产品 css*/
    .remai-content{
        zoom: 1;
    }
    .remai-content:after{
        clear:both;
        content:'';
        display:block;
        width: 0;
        height: 0;
    }
    .remai-content .remai-content-img{
        width: 35%;
        float: left;
        margin-bottom: 10px;
        height: 220px;
    }
    .remai-content .remai-content-img>div{
        padding: 10px;
        border: 1px solid #e5e5e5;
        height: 100%;
    }
    .remai-content .remai-content-img>div img{
        height: 100%;
    }
    .remai-content .remai-content-text{
        width: 65%;
        float: left;
        margin-left: -1px;
        margin-bottom: 10px;
    }
    .remai-content .remai-content-text .remai-content-text-out{
        padding: 10px;
        border: 1px solid #e5e5e5;
        position: relative;
        height: 220px;
    }
    .remai-content-text-title{
        font-size: 18px;
        font-weight: 600;
        padding: 10px 0;
    }
    .remai-content-text-bottom{
        position: absolute;
        bottom: 10px;
        right: 10px;
    }
    .am-comment a{
        color: #6d6d6d !important;
    }
    .am-comment-primary .am-comment-avatar,.am-comment-primary .am-comment-main{
        border-color: #c5c5c5;
    }
    .am-comment-primary .am-comment-main:before{
        border-right-color: #9c9c9c;
    }
    .am-popup-bd{
        background-color: white;
    }
    .border-red{
        border: 1px solid #ca0000 !important;
    }
    .am-comments-list{
        padding: 10px;
        border: 1px solid lightgray;
    }
    .am-btn{
        padding: 0 1rem;
        line-height: 1.4;
    }
</style>
<!--内容-->
<div id="demo">
    <div class="content" >
        <div style="height: 200px;background: url('../image/tv_ds.jpg') no-repeat;background-size: cover;">
            <div class="toubulog" style="position: relative;">
                <div style="position: absolute;bottom: 0;">
                    <form id="formToUpdate" method="post" action="#" enctype="multipart/form-data" style="position: absolute;">
                        <input type="file" class="op-0" id="file_toget" name="upfile" style="opacity: 0;width: 100px;height: 100px;cursor: pointer;">
                    </form>
                    <img class="fl-left" :src="grzl.txtp" width="100" height="100">
                    <div class="fl-left" style="width: 300px;color: white;margin-left: 10px;">
                        <div style="margin-bottom: 10px;">昵称：{{ grzl.mc }}</div>
                        <div>电话：{{ grzl.sj }}</div>
                    </div>
                </div>
            </div>
        </div>
        <div style="max-width: 1200px;min-width: 400px;margin: 0 auto;">
            <div class="gr-nav">
                <span class="span-active" tab="1">个人资料</span>
                <span tab="2">我的图片</span>
                <span tab="3">我的活动</span>
                <span tab="4">站内信</span>
            </div>
            <div class="tab-out">
                <!--个人资料页-->
                <div class="tab1" style="display: block;">
                    <form class="am-form am-form-horizontal" id="grzl">
                        <div class="am-form-group">
                            <label for="doc-ipt-cont-3" class="am-u-sm-4 am-form-label">账号：</label>
                            <div class="am-u-sm-6">
                                <input type="text" id="doc-ipt-cont-3" name="bh" placeholder="账号" value="{{ grzl.bh }}" readonly>
                            </div>
                        </div>

                        <div class="am-form-group">
                            <label for="doc-ipt-liebie-2" class="am-u-sm-4 am-form-label">用户类别：</label>
                            <div class="am-u-sm-6">
                                <input type="tel" id="doc-ipt-liebie-2" name="lx" placeholder="用户类别" value="{{ grzl.lx =='N'?'普通用户':'摄影师' }}" readonly >
                            </div>
                        </div>

                        <div class="am-form-group">
                            <label for="doc-ipt-3" class="am-u-sm-4 am-form-label">昵称：</label>
                            <div class="am-u-sm-6">
                                <input type="text" id="doc-ipt-3" name="mc" placeholder="昵称" value="{{ grzl.mc }}">
                            </div>
                        </div>

                        <div class="am-form-group">
                            <label for="doc-ipt-pwd-2" class="am-u-sm-4 am-form-label">真实名字：</label>
                            <div class="am-u-sm-6">
                                <input type="text" id="doc-ipt-pwd-2" placeholder="真实名字">
                            </div>
                        </div>

                        <div class="am-form-group">
                            <label for="doc-ipt-tel-2" class="am-u-sm-4 am-form-label">手机：</label>
                            <div class="am-u-sm-6">
                                <input type="number" id="doc-ipt-tel-2" name="sj" placeholder="手机" value="{{ grzl.sj }}">
                            </div>
                        </div>

                        <div class="am-form-group">
                            <label for="doc-ipt-mail-2" class="am-u-sm-4 am-form-label">邮箱：</label>
                            <div class="am-u-sm-6">
                                <input type="email" id="doc-ipt-mail-2" name="mail" placeholder="邮箱" value="{{ grzl.mail }}">
                            </div>
                        </div>

                        <div class="am-form-group">
                            <label class="am-u-sm-4 am-form-label">性别：</label>
                            <div class="am-u-sm-6">
                                <div class="am-form-group" style="margin: 0;padding-top: 0.65rem;">
                                    <label class="am-radio-inline">
                                        <input type="radio" name="xb" value="男" v-model="grzl.xb" class="am-ucheck-radio">
                                        <span class="am-ucheck-icons">
                                  <i class="am-icon-unchecked"></i>
                                  <i class="am-icon-checked"></i>
                               </span>
                                        男
                                    </label>
                                    <label class="am-radio-inline">
                                        <input type="radio" name="xb" value="女" v-model="grzl.xb" class="am-ucheck-radio">
                                        <span class="am-ucheck-icons">
                                  <i class="am-icon-unchecked"></i>
                                  <i class="am-icon-checked"></i>
                               </span>
                                        女
                                    </label>
                                    <label class="am-radio-inline">
                                        <input type="radio" name="xb" value="保密" v-model="grzl.xb" class="am-ucheck-radio">
                                        <span class="am-ucheck-icons">
                                  <i class="am-icon-unchecked"></i>
                                  <i class="am-icon-checked"></i>
                               </span>
                                        保密
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="am-form-group">
                            <div class="am-u-sm-6 am-u-sm-offset-4">
                                <div class="am-btn am-btn-success" onclick="grzlbc()">保 存</div>
                                <div class="am-btn am-btn-secondary am-fr" onclick="myindex({{grzl.rid}})">我的主页</div>
                            </div>
                        </div>
                    </form>
                </div>
                <!--我的图片页-->
                <div class="tab2">
                    <div style="margin-bottom: 10px;">
                        <!--<label>-->
                        <!--<input type="checkbox"> 全部选中-->
                        <!--</label>-->
                        <!--<span class="sanchu">删 除</span>-->
                        <span id="add-img" class="sanchu"  data-am-modal="{target: '#doc-modal-1', closeViaDimmer: 0, width: 400, height: 225}" style="background-color: #00adee">+ 新增</span>
                    </div>
                    <div id="freewall" class="free-wall"></div>
                </div>
                <!--我的活动页-->
                <div class="tab3">
                    <div class="remai-content">
                        <div class="clear-both remai-content-img">
                            <div>
                                <img src="../image/tv1_03.png" width="100%" height="200">
                            </div>
                        </div>
                        <div class="clear-both remai-content-text">
                            <div class="remai-content-text-out">
                                <div>
                                    <span class="biaoqian">路线</span>
                                </div>
                                <div class="remai-content-text-title">
                                    <span style="display: inline-block;width: 80%">台湾台北旧城老街之艋舺古迹巡礼半日游</span>
                                    <span class="fl-right">888元</span>
                                </div>
                                <div class="remai-content-text-content">
                                    花街里的风雅历史，明治遗风下的生活定格一道坡，数小巷，细石板路上走出的怀旧和风VERONICA说，庶民的东京说的都是情
                                </div>
                                <div class="remai-content-text-bottom">
                                    <span class="ckxq" style="background: #e69d3b;"><a href="m2hdxq.php">查看详情</a></span>
                                    <span class="ljgm" style="background: #3ec9e6;">已参加</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--站内信页-->
                <div class="tab4">
                    <ul class="am-comments-list am-comments-list-flip" v-for="(index,sg) in msg">
                        <div v-for="bk in sg.sub">
                            <li class="am-comment" v-if="bk.usid!=grzl.rid">
                                <img :src="bk.txtp" alt="" class="am-comment-avatar" width="48" height="48">
                                <div class="am-comment-main">
                                    <header class="am-comment-hd">
                                        <div class="am-comment-meta">
                                            评论于
                                            <time>
                                                {{ bk.cj_rq }}
                                            </time>
                                        </div>
                                        <div class="am-comment-actions">
                                            <a style="cursor: pointer;" onclick="hf({{ bk.usid }},{{ sg.rid }},{{ index }})">
                                                <i class="am-icon-pencil"></i>
                                            </a>
                                        </div>
                                    </header>
                                    <div class="am-comment-bd">
                                        <p>
                                            {{ bk.msg }}
                                        </p>
                                    </div>
                                </div>
                            </li>
                            <li v-else class="am-comment am-comment-flip am-comment-secondary">
                                <img :src="grzl.txtp" alt="" class="am-comment-avatar" width="48" height="48">
                                <div class="am-comment-main">
                                    <header class="am-comment-hd">
                                        <div class="am-comment-meta">
                                            评论于
                                            <time>
                                                {{ bk.cj_rq }}
                                            </time>
                                        </div>
                                    </header>
                                    <div class="am-comment-bd">
                                        <p>
                                            {{ bk.msg }}
                                        </p>
                                    </div>
                                </div>
                            </li>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="doc-modal-1" tabindex="-1" class="am-popup" >
    <div class="am-popup-inner">
        <div class="am-popup-hd">
            <h4 class="am-popup-title">图片上传</h4>
            <span data-am-modal-close class="am-close">&times;</span>
        </div>
        <div class="am-popup-bd">
            <div class="am-form am-form-horizontal" style="margin-top: 10px;">
                <div class="am-form-group">
                    <label class="am-u-sm-3 am-form-label">图片上传：</label>
                    <div class="am-u-sm-9">
                        <div class="am-input-group">
                            <input type="text" class="am-form-field" placeholder="图片文件名" name="tp" readonly>
                            <div class="am-input-group-btn">
                                <div class="am-btn am-btn-default">
                                    上传图片
                                    <form id="formToUpdate1" method="post" action="#" enctype="multipart/form-data">
                                        <input type="file" id="file_toget1" name="upfile" multiple style="opacity:0;position: absolute;width: 96px;left: 0;height: 36px;top: 0;">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <form class="am-form am-form-horizontal" id="tpsc">
                <div class="am-form-group">
                    <label for="doc-ipt-bt-2" class="am-u-sm-3 am-form-label">标题：</label>
                    <div class="am-u-sm-9">
                        <input type="text" id="doc-ipt-bt-2" placeholder="标题" name="bt">
                    </div>
                </div>
                <div class="am-form-group">
                    <label for="doc-ipt-sm-2" class="am-u-sm-3 am-form-label">说明：</label>
                    <div class="am-u-sm-9">
                        <textarea style="resize:none;" id="doc-ipt-sm-2" placeholder="说明" name="js"></textarea>
                    </div>
                </div>
                <div class="am-form-group">
                    <label class="am-u-sm-3 am-form-label">标签：</label>
                    <div class="am-u-sm-9">
                        <select data-placeholder="请选择..." class="chzn-select" multiple id="dl_chose1" readonly></select>
                    </div>
                </div>
                <div class="am-form-group">
                    <div class="am-u-sm-9 am-u-sm-offset-3">
                        <div  class="am-btn am-btn-success" onclick="bctp()">提交保存</div>
                    </div>
                </div>
                <div class="am-form-group">
                    <label class="am-u-sm-3 am-form-label"></label>
                    <div class="am-u-sm-9">
                        <div>
                            <img id="zstp" src="" width="100%">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="doc-modal-2" tabindex="-1" class="am-popup" >
    <div class="am-popup-inner">
        <div class="am-popup-hd">
            <h4 class="am-popup-title">图片编辑</h4>
            <span data-am-modal-close class="am-close">&times;</span>
        </div>
        <div class="am-popup-bd">
            <div class="am-form am-form-horizontal" style="margin-top: 10px;">
                <div class="am-form-group">
                    <label class="am-u-sm-3 am-form-label">图片上传：</label>
                    <div class="am-u-sm-9">
                        <input type="text" class="am-form-field" value="{{ sgdata.tp }}" placeholder="图片文件名" name="tp1" readonly>
                    </div>
                </div>
            </div>
            <form class="am-form am-form-horizontal" id="tpsc1">
                <div class="am-form-group">
                    <label for="doc-ipt-bt-3" class="am-u-sm-3 am-form-label">标题：</label>
                    <div class="am-u-sm-9">
                        <input type="text" id="doc-ipt-bt-3" value="{{ sgdata.bt }}" placeholder="标题" name="bt">
                    </div>
                </div>
                <div class="am-form-group">
                    <label for="doc-ipt-sm-3" class="am-u-sm-3 am-form-label">说明：</label>
                    <div class="am-u-sm-9">
                        <textarea style="resize:none;" id="doc-ipt-sm-3"  placeholder="说明" name="js">{{ sgdata.js }}</textarea>
                    </div>
                </div>
                <div class="am-form-group">
                    <label class="am-u-sm-3 am-form-label">标签：</label>
                    <div class="am-u-sm-9">
                        <select data-placeholder="请选择..." class="chzn-select" multiple  id="dl_chose2" readonly></select>
                    </div>
                </div>
                <div class="am-form-group">
                    <div class="am-u-sm-9 am-u-sm-offset-3">
                        <div v-if="sgdata.zt==1" class="am-btn am-btn-success" onclick="xgtp({{ sgdata.rid }})">提交修改</div>
                        <div v-if="sgdata.zt!=0" class="am-btn am-btn-danger am-fr" onclick="sctp({{ sgdata.rid }})">删除此图</div>
                    </div>
                </div>
                <div class="am-form-group">
                    <label class="am-u-sm-3 am-form-label"></label>
                    <div class="am-u-sm-9">
                        <div>
                            <img id="zstp1" :src="sgdata.tp" width="100%">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript" src="../js/jquery-1.9.1.js"></script>
<script type="text/javascript" src="../js/freewall.js"></script>
<script type="text/javascript" src="../js/amazeui.min.js"></script>
<script type="text/javascript" src="../js/chosen.jquery.js"></script>
<script type="text/javascript" src="../js/jquery.form.js"></script>
<script type="text/javascript" src="../js/jquery.cookie.js"></script>
<script type="text/javascript" src="../js/common.js"></script>
<script type="text/javascript" src="../js/vue.js"></script>
<script type="text/javascript" src="../layer/layer.js"></script>
<script>
    var sign1=$.cookie('sign');
    var sign=URLencode(sign1);
    var picdata;
    var uid;
    var wall = new Freewall("#freewall");
    var demo = new Vue({
        el: '#demo',
        data: {
            grzl: [],
            tppic: [],
            msg: [],
            bq: [],
            sgdata: {}
        }
    });
    $(function () {
        $.ajax({
            type: "get",
            url: G_url + 'tvus/get?sign=' + sign,
            dataType: "json",
            async:false,
            success: function (res) {
                if (res.ok) {
                    demo.grzl=res.data;
                    demo.tppic=res.pic;
                    demo.msg=res.msg;
                    demo.bq=res.bq;
                    uid=res.data.rid;
                    picdata=res.pic;
                    if(res.data.txtp==null){
                        demo.grzl.txtp='../image/logo.jpg';
                    }
                    fuzhiBq('',1);
                } else {
                    alert('数据获取出错请刷新!!')
                }
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                //f_toast_show('close','操作失败!');
            }
        });
        $('.gr-nav span').click(function () {
            var index=$(this).attr('tab');
            $('.gr-nav span').removeClass('span-active');
            $(this).addClass('span-active');
            $('.tab-out>div').hide();
            $('.tab'+index).fadeIn();
            if(index==2){
                f_freewall();
            }
        });
    });


    function f_freewall() {
        var temp = "<div class='cell' data-am-modal='{target: \"#doc-modal-2\", closeViaDimmer: 0, width: 400, height: 225}' data-index='{index}' style='overflow: hidden;position: relative;border: 1px solid lightgray;width:{width}px; height: {height}px; background-image: url({bgurl});background-size: 100%;background-position: center;background-repeat: no-repeat;'>" +
            "<div class='{class}' style='box-shadow: 0 0 10px #888;transform: rotate(45deg);color: white;position: absolute;top: 15px;right: -32px;text-align: center;width: 120px;'>{text}</div>"+
            "</div>";
        var w = 200, h = 200, html = '', limitItem = demo.tppic.length,zt,cla;
        for (var i = 0; i < limitItem; ++i) {
            if(demo.tppic[i].zt=='-1'){
                zt='驳回';
                cla='am-badge-danger';
            }else if(demo.tppic[i].zt=='0'){
                zt='待审核';
                cla='am-badge-warning';
            }else if(demo.tppic[i].zt=='1'){
                zt='审核通过';
                cla='am-badge-success';
            }
            html += temp.replace(/\{height\}/g, h)
                .replace(/\{width\}/g, w)
                .replace("{bgurl}", demo.tppic[i].tp)
                .replace("{text}", zt)
                .replace("{class}", cla)
                .replace("{index}", demo.tppic[i].rid);
        }
        $("#freewall").html(html);
        wall.reset({
            selector: '.cell',
            animate: true,
            cellW: 200,
            cellH: 200,
            onResize: function() {
                wall.refresh();
            }
        });
        wall.fitWidth();
        //点击图片编辑
        $('#freewall>.cell').click(function () {
            var index=$(this).attr('data-index'),strTem;
            for(var i=0;i<demo.tppic.length;i++){
                if(index==demo.tppic[i].rid){
                    demo.sgdata=demo.tppic[i];
                    strTem=demo.sgdata.bq.split(',');
                }
            }
            fuzhiBq(strTem,2);
        });
    }

    //点击图片修改的方法
    function fuzhiBq(values,id){
        var length = values.length;
        var html;
        $.each(demo.bq, function (a, b){//直接取出json的prolist做each循环.
            html += "<option value='"+b.mc+"'>" + b.mc + "</option>";//拼接字符串.
        });
        $("#dl_chose"+id).html(html);
        for (var i = 0; i < length; i++) {
            $("#dl_chose"+id +" option[value='" + values[i] + "']").attr('selected', 'selected');
        }
        $("#dl_chose"+id).trigger("chosen:updated");
        $("#dl_chose"+id).chosen();
    }

    // for scroll bar appear;
    $(window).trigger("resize");


    //H5图像
    $("#file_toget").change(function(){
        var objUrl = getObjectURL(this.files[0]) ;
        commonUrl=objUrl;
//        alert(commonUrl);
        console.log("objUrl = "+objUrl) ;
        if (objUrl) {
            fileonchange();
        }
    }) ;
    $("#file_toget1").change(function(){
        var objUrl = getObjectURL(this.files[0]) ;
        commonUrl=objUrl;
//        alert(commonUrl);
        console.log("objUrl = "+objUrl) ;
        if (objUrl) {
            fileonchange1();
        }
    }) ;
    //建立一個可存取到該file的url
    function getObjectURL(file) {
        var url = null ;
        if (window.createObjectURL!=undefined) { // basic
            url = window.createObjectURL(file) ;
        } else if (window.URL!=undefined) { // mozilla(firefox)
            url = window.URL.createObjectURL(file) ;
        } else if (window.webkitURL!=undefined) { // webkit or chrome
            url = window.webkitURL.createObjectURL(file) ;
        }
        return url ;
    }
    var fileonchange=function(){
//        alert('函数内');
        $('#formToUpdate').ajaxSubmit({
            type:'post',
            dataType:'json',
            url:G_url_im+'imgsqt/uptx?sign='+sign,
            beforeSend:function(){
            },
            uploadProgress: function(event, position, total, percentComplete){
            },
            error:function(data){
            },
            success:function(result){
                //获取文件名的正则表达式
                var file = result.pic;
                if(result.ok==false){
                    layer.msg(result.msg);
                }else {
                    demo.grzl.txtp=file;
                }
            }
        });
    };
    var fileonchange1=function(){
//        alert('函数内');
        $('#formToUpdate1').ajaxSubmit({
            type:'post',
            dataType:'json',
            url:G_url_im+'imgsqt/up?sign='+sign,
            beforeSend:function(){

            },
            uploadProgress: function(event, position, total, percentComplete){

            },
            error:function(data){

            },
            success:function(result){
                //获取文件名的正则表达式
                var file = result.pic;
                if(result.ok==false){
                    layer.msg(result.msg);
                }else {
                    $('#zstp').attr('src',file);
                    $('input[name="tp"]').val(file);
                }
            }
        });
    };
    function bctp() {
        var text='';
        $('#dl_chose1_chosen>ul>li').each(function () {
            if($(this).children('span').html()==undefined){
                return;
            }
            text+=$(this).children('span').html()+',';
        });
        text=text.substring(0,text.length-1);
        if($('input[name="tp"]').val()==''||$('input[name="bt"]').val()==''||text==''){
            layer.msg('内容不能为空');
        }else {
            $.ajax({
                type: "post",
                url: G_url + 'doi_usid/add/tvup?sign='+sign,
                data:'usid='+uid+'&'+$('#tpsc').serialize()+'&tp='+$('input[name="tp"]').val()+'&bq='+text,
                dataType: "json",
                success: function (res) {
                    if (res.ok) {
                        $('.am-close').trigger('click');
                        demo.tppic=demo.tppic.reverse();
                        demo.tppic.push(res.data);
                        demo.tppic=demo.tppic.reverse();
                        fuzhiBq('',1);
                        f_freewall();
                    } else {
                        alert('数据获取出错请刷新')
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    //f_toast_show('close','操作失败!');
                }
            });
        }
    }
    function xgtp(a) {
        var text='';
        $('#dl_chose2_chosen>ul>li').each(function () {
            if($(this).children('span').html()==undefined){
                return;
            }
            text+=$(this).children('span').html()+',';
        });
        text=text.substring(0,text.length-1);
        if(text==''){
            layer.msg('修改内容不能为空');
        }else {
            $.ajax({
                type: "post",
                url: G_url + 'doi_usid/edit/tvup?sign='+sign,
                data:'usid='+uid+'&rid='+a+'&'+$('#tpsc1').serialize()+'&tp='+$('input[name="tp1"]').val()+'&bq='+text,
                dataType: "json",
                success: function (res) {
                    if (res.ok) {
                        $('.am-close').trigger('click');
                        //修改图片数据
                        for(var m=0;m<demo.tppic.length;m++){
                            if(demo.tppic[m].rid == a){
                                demo.tppic[a].bt=res.data.bt;
                                demo.tppic[a].js=res.data.js;
                                demo.tppic[a].bq=res.data.bq;
                            }
                        }
                        //修改图片数据结束
                        layer.msg('修改成功', {icon: 1,time: 200});
                    } else {
                        alert('数据获取出错请刷新')
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    //f_toast_show('close','操作失败!');
                }
            });
        }
    }
    function sctp(b) {
        layer.confirm('确定删除此图片？', {
                btn: ['确定','取消'] //按钮
            }, function(){
                $.ajax({
                    type: "post",
                    url: G_url + 'doi_usid/dels/tvup?sign='+sign,
                    data:'usid='+uid+'&rid='+b,
                    dataType: "json",
                    success: function (res) {
                        if (res.ok) {
                            $('.am-close').trigger('click');
                            for(var m=0;m<demo.tppic.length;m++){
                                if(demo.tppic[m].rid == b){
                                    demo.tppic.splice(m,1);
                                }
                            }
                            f_freewall();
                            layer.msg('删除成功', {icon: 1,time: 200});
                        } else {
                            alert('数据获取出错请刷新');
                        }
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        //f_toast_show('close','操作失败!');
                    }
                });
            }, function(){}
        );
    }
    function grzlbc() {
        $.ajax({
            type: "post",
            url: G_url + 'tvus/edit?sign='+sign,
            data:'rid='+uid+'&'+$('#grzl').serialize(),
            dataType: "json",
            success: function (res) {
                if (res.ok) {
                    layer.msg('保存成功', {icon: 1});
                } else {
                    alert('数据获取出错请刷新')
                }
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                //f_toast_show('close','操作失败!');
            }
        });
    }
    function hf(c,d,e) {
        layer.prompt({title: '回复的话', formType: 2}, function(text, index){
            $.ajax({
                type: "post",
                url: G_url + 'doi_usid/add/tvms?sign='+sign,
                data:'usid2='+c+'&pid='+d+'&msg='+text,
                dataType: "json",
                async:false,
                success: function (res) {
                    if (res.ok) {
                        demo.msg[e].sub.push(res.data);
                        layer.close(index);
                    } else {
                        alert('数据获取出错请刷新')
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    //f_toast_show('close','操作失败!');
                }
            });
        });
    }
    function myindex(n) {
        //location.href='sys_gr.php?rid='+n;
        location.href='sys_gr_jk.php?rid=1'

    }
</script>